name: SimpleBombs
author: M0dii
main: me.m0dii.bombs.SimpleBombs
version: ${version}
softdepend: [WorldGuard, WorldEdit, HolographicDisplays, DecentHolograms, PlaceholderAPI]
api-version: 1.13
commands:
  simplebombs:
    description: Main command.
    permission: simplebombs.use
    aliases: [bomb, spb]